### ISSUE TITLE
使用不能

### ISSUE THREAD

**Issue by yukinahimeragi** [vzvu3k6k/asahi-ajax_more.user.js#1]
現時点でこのスクリプトが使えなくなりました。この先更新する予定があるのでしょうか。

**Comment by vzvu3k6k** [comment]
#2 で修正しました。不具合が残っていたらreopenするか新規のissueを立ててください。

今後の更新予定については、不具合報告があれば対応するかもしれない、というぐらいです。

**Comment by yukinahimeragi** [comment]
www.asahi.comにリダイレクトされたんですが、どうすればいいですか。

**Comment by vzvu3k6k** [comment]
別の問題のようなので #4 を作りました。現状ではこちらでは再現できていないので対応は難しいと思います。
使用しているブラウザの名称とバージョン、ブラウザ拡張の名称とバージョンを教えてもらえれば、時間のあるときに対応できるかもしれません。

**Comment by yukinahimeragi** [comment]
ブラウザーはgoogle chrome 73.0.3683.86（正式版） （64 ビット）
ブラウザー拡張はtampermonkey v4.8
よろしくお願いします。
